language: node_js

node_js:
  - "11.3.0"

branches:
  only:
    - develop

install:
  - npm install

script:
  - npm run build
  
after_success:
  - cd ./dist
  - git init
  - git config --global user.name "wuhaohao1234"
  - git config --global user.email "1611499758@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/wuhaohao1234/node-server